/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaExperto;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;



/**
 *
 * @author Robles
 */
public class Evaluacion extends javax.swing.JFrame {

    /**
     * Creates new form Evaluacion
     */
    public Evaluacion() {
        initComponents();
        grupo1.add(si1);
        grupo1.add(no1);
        grupo2.add(si2);
        grupo2.add(no2);
        grupo3.add(si3);
        grupo3.add(no3);
        grupo4.add(si4);
        grupo4.add(no4);
        grupo5.add(si5);
        grupo5.add(no5);
        grupo6.add(si6);
        grupo6.add(no6);
        grupo7.add(si7);
        grupo7.add(no7);
        grupo8.add(si8);
        grupo8.add(no8);
        grupo9.add(si9);
        grupo9.add(no9);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        si1 = new javax.swing.JRadioButton();
        no1 = new javax.swing.JRadioButton();
        si2 = new javax.swing.JRadioButton();
        si7 = new javax.swing.JRadioButton();
        si3 = new javax.swing.JRadioButton();
        si4 = new javax.swing.JRadioButton();
        si5 = new javax.swing.JRadioButton();
        si8 = new javax.swing.JRadioButton();
        si6 = new javax.swing.JRadioButton();
        si9 = new javax.swing.JRadioButton();
        no2 = new javax.swing.JRadioButton();
        no4 = new javax.swing.JRadioButton();
        no3 = new javax.swing.JRadioButton();
        no5 = new javax.swing.JRadioButton();
        no6 = new javax.swing.JRadioButton();
        no7 = new javax.swing.JRadioButton();
        no8 = new javax.swing.JRadioButton();
        no9 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evaluacion");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Evaluacion"));

        jLabel1.setText("1.¿A menudo no presta atención suficiente a los detalles o incurre en errores por descuido en las tareas escolares, en el trabajo o en otras actividades?");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("2.¿A menudo tiene dificultades para mantener la atención en tareas o en actividades lúdicas?");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("4.¿A menudo mueve en excesos las manos o los pies o se remueve en el asiento?");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("5.¿A menudo habla en exceso?");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("6.¿A menudo 'está en marcha' o actúa como si 'tuviera un motor?");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setText("7.¿A menudo tiene dificultades para guardar turno?");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("8. A menudo interrumpe o se inmiscuye en las actividades de otros (p.ej., se entromete en conversaciones o juegos)");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("9.¿A menudo precipita respuestas antes de haber sido completadas las preguntas?");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("3.¿A menudo parece no escuchar cuando se le habla directamente?");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        si1.setText("Si");

        no1.setText("No");

        si2.setText("Si");

        si7.setText("Si");

        si3.setText("Si");

        si4.setText("Si");

        si5.setText("Si");

        si8.setText("Si");

        si6.setText("Si");

        si9.setText("Si");

        no2.setText("No");

        no4.setText("No");

        no3.setText("No");

        no5.setText("No");

        no6.setText("No");

        no7.setText("No");

        no8.setText("No");

        no9.setText("No");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(si1)
                                .addGap(108, 108, 108)
                                .addComponent(no1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(si2)
                            .addComponent(si8)
                            .addComponent(si3)
                            .addComponent(si7)
                            .addComponent(si4)
                            .addComponent(si5)
                            .addComponent(si6)
                            .addComponent(si9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no4)
                            .addComponent(no2)
                            .addComponent(no3)
                            .addComponent(no5)
                            .addComponent(no6)
                            .addComponent(no7)
                            .addComponent(no8)
                            .addComponent(no9))
                        .addGap(21, 21, 21))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si1)
                    .addComponent(no1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(si2)
                    .addComponent(no2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(si3)
                    .addComponent(no3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(si4)
                    .addComponent(no4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(si5)
                    .addComponent(no5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(si6)
                    .addComponent(no6))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(si7)
                    .addComponent(no7))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(si8)
                    .addComponent(no8))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(si9)
                    .addComponent(no9)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String Fichero= "entradas.txt";
        String res="", s="",n="";
            try {
                BufferedWriter bw = new BufferedWriter(new FileWriter(Fichero));
                if(si1.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                if (no1.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                if(si2.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                else if(no2.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                 if(si3.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                 else if(no3.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                 if(si4.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                 else if(no4.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                 if(si5.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                 else if(no5.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                 if(si6.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                 else if(no6.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                 if(si7.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                 else if(no7.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                 if(si8.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                 else if(no8.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                 if(si9.isSelected()==true){
                    s="1";
                    res+=s+"";
                }
                 else if(no9.isSelected()==true){
                    n="0";
                    res+=n+"";
                }
                 System.out.println(""+res);
                 bw.write(res);
                 JOptionPane.showMessageDialog(null, "Se a guardado la evaluación");
                 
                 
                 bw.close();
                 this.setVisible(false);
                 Opcion op=new Opcion();
                 op.setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Evaluacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    static ButtonGroup grupo1 = new ButtonGroup();
    static ButtonGroup grupo2 = new ButtonGroup();
    static ButtonGroup grupo3 = new ButtonGroup();
    static ButtonGroup grupo4 = new ButtonGroup();
    static ButtonGroup grupo5 = new ButtonGroup();
    static ButtonGroup grupo6 = new ButtonGroup();
    static ButtonGroup grupo7 = new ButtonGroup();
    static ButtonGroup grupo8 = new ButtonGroup();
    static ButtonGroup grupo9 = new ButtonGroup();
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Evaluacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Evaluacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton no1;
    private javax.swing.JRadioButton no2;
    private javax.swing.JRadioButton no3;
    private javax.swing.JRadioButton no4;
    private javax.swing.JRadioButton no5;
    private javax.swing.JRadioButton no6;
    private javax.swing.JRadioButton no7;
    private javax.swing.JRadioButton no8;
    private javax.swing.JRadioButton no9;
    private javax.swing.JRadioButton si1;
    private javax.swing.JRadioButton si2;
    private javax.swing.JRadioButton si3;
    private javax.swing.JRadioButton si4;
    private javax.swing.JRadioButton si5;
    private javax.swing.JRadioButton si6;
    private javax.swing.JRadioButton si7;
    private javax.swing.JRadioButton si8;
    private javax.swing.JRadioButton si9;
    // End of variables declaration//GEN-END:variables
}
